### ISSUE TITLE
 h02 Protocol

### ISSUE THREAD

**Issue by a1ad** [AlexanderBekrenev/gps2nextcloud#1]
@AlexanderBekrenev: i would like to test a tracker with the h02 protocol. Is it a lot of work to implement it?

**Comment by AlexanderBekrenev** [comment]
I look at this protocol. As I understand it, it is possible to realize only a small part that PhoneTrack understands. This is the transfer of coordinates and battery charge. h02 protocol has extended data for vehicle state and it has commands part. But PhoneTrack does not support it.
So, if you have examples of tracker messages, then the basic implementation should not be very complicated.

**Comment by AlexanderBekrenev** [comment]
You can try version 0.1.7 but I have not tracker with H02 protocol. So it is only by documentation.

**Comment by a1ad** [comment]
Hi, i am 2 weeks on vacation right now. I am going to test the protocol when back.

**Comment by a1ad** [comment]
Hi,

I get the follow error:
Command: /usr/bin/python3 /usr/local/lib/python3.6/site-packages/gps2nextcloud/server.py --config_file /etc/gps2nextcloud/gps2nextcloud.ini
  
Error:
 File "/usr/local/lib/python3.6/site-packages/gps2nextcloud/server.py", line 104
    server = Process(target=server_func, name=f"gps2nextcloud_{section}", args=(config_path, section,))
                                                                       ^
SyntaxError: invalid syntax

My config looks like this:
[General]
loglevel = INFO

[DummyGate]
host = 0.0.0.0
port = 5009
protocol = base:ProtocolBase
gate = base:DummyGate

[h02Gate]
host = 0.0.0.0
port = 5012
protocol = h02_protocol:H02Protocol
gate = http_gate:HttpGate
url = **redacted**

Debian 8 with python3.6

**Comment by AlexanderBekrenev** [comment]
I change f-strings and imports. New version is 0.1.8.

**Comment by a1ad** [comment]
Thanks, now it is working. I am going to test it a couple of days and let you know! Thanks a lot.

**Comment by AlexanderBekrenev** [comment]
I will wait for the news. Python is new language for me.

**Comment by a1ad** [comment]
There is a location offset now. When i use traccar or sms location i get the exact location. But when i use your program there is a offset of about +-500m and it is fluctuating. Maybe a rounding error? Can i send you some debug info?

Here` is some debug info from my tracker, i was debugging the messages before your program:

```
2a48512c343231303230353832322c56342c56312c323031393037313532313230343423
*HQ,4210205822,V4,V1,20190715212044#


2a48512c343231303230353832322c23
*HQ,4210205822,#


2a48512c343231303230353832322c56312c3231323034342c562c353034392e393134392c4e2c30303434322e303831362c452c3030302e30302c3030302c3135303731392c46464537464246462c3230362c31302c302c302c36232a48512c343231303230353832322c56342c56312c323031393037313532313234303023
*XX,YYYYYYYYYY,V1,HHMMSS,S,latitude,D,longitude,G,speed,direction,DDMMYY,vehicle_status#
*HQ,4210205822,V1,212044,V,5049.9149,N,00442.0816,E,000.00,000,150719,FFE7FBFF,206,10,0,0,6#
*HQ,4210205822,V4,V1,20190715212400#

```

**Comment by AlexanderBekrenev** [comment]
Last data with coordinates. gps2nextcloud parse it to string
'*HQ,4210205822,V1,212044,V,5049.9149,N,00442.0816,E,000.00,000,150719,FFE7FBFF,206,10,0,0,6#'
Here as I see we have 5049.9149,N,00442.0816,E that is 
North 50 degrees and 49.9149 minutes
East 4 degrees and 42.0816 minutes

So program gets from string next data:
client_id: 4210205822 2019-07-15 21:20:44 Fix:False Lat:50.831915 Lon:4.70136
How accurate are the coordinates?

For the most successful debugging I need log with DEBUG level message 'received buffer:' and correct coordinates that we need to get from it.

**Comment by a1ad** [comment]
Hi,

The Debug log:

```
[INFO/gps2nextcloud_h02Gate] child process calling self.run()
[INFO/gps2nextcloud_h02Gate] listening on 0.0.0.0:5013
[INFO/gps2nextcloud_h02Gate] accepted connection from ('*.*.*.*', 29424)
[DEBUG/gps2nextcloud_h02Gate] received buffer: '2a48512c343231303230353832322c56312c3039333632392c412c353034352e303534332c4e2c30303432302e313830312c452c3030302e30302c3030302c3034303931392c46464537464246462c3230362c31302c302c302c3623'
[DEBUG/gps2nextcloud_h02Gate] parsing '*HQ,4210205822,V1,093629,A,5045.0543,N,00420.1801,E,000.00,000,040919,FFE7FBFF,206,10,0,0,6#'
[DEBUG/gps2nextcloud_h02Gate] get: https://******/nextcloud/apps/phonetrack/logGet/d1ec74b2ba2b51189bee4096aa688449/4210205822?lat=50.750905&lon=4.336335&alt=0.0&bat=206&sat=0&speed=0.0&bearing=0.0&timestamp=1567589789.0
[DEBUG/gps2nextcloud_h02Gate] response: 200: b'{"done":1,"friends":[]}'
[DEBUG/gps2nextcloud_h02Gate] received buffer: '2a48512c343231303230353832322c23'
[DEBUG/gps2nextcloud_h02Gate] parsing '*HQ,4210205822,#'
[DEBUG/gps2nextcloud_h02Gate] Unknown version '#'
[DEBUG/gps2nextcloud_h02Gate] received buffer: '2a48512c343231303230353832322c56312c3039333633302c412c353034352e303534332c4e2c30303432302e313830312c452c3030302e30302c3030302c3034303931392c46464537464246462c3230362c31302c302c302c3623'
[DEBUG/gps2nextcloud_h02Gate] parsing '*HQ,4210205822,V1,093630,A,5045.0543,N,00420.1801,E,000.00,000,040919,FFE7FBFF,206,10,0,0,6#'
[DEBUG/gps2nextcloud_h02Gate] get: https://******nextcloud/apps/phonetrack/logGet/d1ec74b2ba2b51189bee4096aa688449/4210205822?lat=50.750905&lon=4.336335&alt=0.0&bat=206&sat=0&speed=0.0&bearing=0.0&timestamp=1567589790.0
[DEBUG/gps2nextcloud_h02Gate] response: 200: b'{"done":1,"friends":[]}'
[DEBUG/gps2nextcloud_h02Gate] received buffer: '2442102058220936310409195045054006004201800e000000ffe7fbffff001909000003af00ce0a000000005c'
[DEBUG/gps2nextcloud_h02Gate] parsing '24:42:10:20:58:22:09:36:31:04:09:19:50:45:05:40:06:00:42:01:80:0e:00:00:00:ff:e7:fb:ff:ff:00:19'
[DEBUG/gps2nextcloud_h02Gate] get: https://*************/nextcloud/apps/phonetrack/logGet/d1ec74b2ba2b51189bee4096aa688449/4210205822?lat=50.7509&lon=4.342333333333333&alt=0.0&sat=0&speed=0.0&bearing=0.0&timestamp=1567589791.0
[DEBUG/gps2nextcloud_h02Gate] response: 200: b'{"done":1,"friends":[]}'
[DEBUG/gps2nextcloud_h02Gate] sending b'wrong format' to ('*.*.*.*', 29424)
[INFO/gps2nextcloud_h02Gate] closing connection to ('*.*.*.*', 29424)
```

The correct location from sms:
http://maps.google.com/maps?q=50.75095%2c004.33635   V:A,2019-09-04 11:37:23 S:000km/h,Bat:6ACC:off ,4210205822,S20G10;p:20610, l:17200, c:8254

edit:

As you can see, i get 2 good messages but the latest message is in a wrong format and wrong longitude.
Right lon is 4.336335 but latest msg is: lon=4.342333333333333

**Comment by AlexanderBekrenev** [comment]
Fix in version 0.1.9

**Comment by a1ad** [comment]
awesome! It's working like expected.

**Comment by AlexanderBekrenev** [comment]
Nice to know that!
